services:
  odoo_ecom:
    image: "ghcr.io/impress-foods/odoo-ci/py3.10-odoo17.0:latest"
    container_name: odoo17_ecom
    depends_on:
      - postgres_ecom
    ports:
      - "8069:8069" # Odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - .config:/opt/config
      - ./odoo-modules:/opt/addons
      - ./rest-framework:/opt/rest
      - filestore-17:/root/.local/share/Odoo

    environment:  
      - HOST=postgres_ecom
      - USER=odoo
      - PASSWORD=odoo
      - DATABASE=postgres

    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - odoo-network
    command: /opt/odoo-venv/bin/python /opt/odoo/odoo-bin -c /opt/config/odoo17.conf -d odoo17

  postgres_ecom:
    image: postgres:13
    container_name: postgres_ecom
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/opt/pgdata
    volumes:
      - postgres-data:/opt/pgdata
    networks:
      - odoo-network
    restart: unless-stopped

  redis:
      container_name: redis
      image: library/redis:5.0-alpine
      restart: unless-stopped
      ports:
        - 6379:6379
      networks:
        - odoo-network
      volumes:
        - redis_data:/data


volumes:
  odoo-web-data:
  postgres-data:
  filestore-17:
  redis_data:

networks:
  odoo-network:
    driver: bridge
